[package]
name = "hikyeah"
version = "0.3.0"
edition = "2024"

[dependencies]
digest_auth = "0.3.1"
eframe = "0.36.1"
image = { version = "0.25.10", default-features = false, features = ["jpeg"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
ureq = "2"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
md-5 = "0.10"
ffmpeg-next = { version = "9", default-features = false, features = ["codec", "format", "device", "software-scaling"] }

wgpu = { version = "30", default-features = false, features = ["vulkan", "wgsl"] }

[target.'cfg(unix)'.dependencies]
libc = "0.2.189"

[target.'cfg(target_os = "linux")'.dependencies]
ash = "0.38"
